cask_args appdir: '/Applications'
tap 'caskroom/cask'
brew 'hh'
brew 'git'
brew 'flow'
brew 'httpie'
brew 'tree'
brew 'speedtest_cli'
brew 'mackup'
brew 'colordiff'
brew 'postgresql'
brew 'tmux'
brew 'zsh'
